language: csharp
solution: RomanNumber.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore 
 - dotnet build -f netcoreap2.0
 - dotnet test ./RomanNumbersTest/RomanNumbersTest.csproj -f netcoreap2.0
