language: csharp
solution: RomanNumber.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
- dotnet restore
- dotnet test ./RomanNumbersTest/RomanNumbersTest.csproj
- dotnet build -c Release
- dotnet publish -c Release -o ./RomanNumbers/publish
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "/home/travis/build/AlexTeixeira/TravisLearning/RomanNumbers/RomanNumbers/publish/"
  skip_cleanup: true
  on:
    tags: true