language: csharp
solution: RomanNumber.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore 
 - dotnet build -f netcoreapp1.1
 - dotnet test /home/travis/build/AlexTeixeira/TravisLearning/RomanNumbersTest/bin/Debug/netcoreapp1.1/RomanNumbersTest.dll
