language: csharp
solution: RomanNumber.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore 
 - dotnet build -f netcoreapp2.0
 - dotnet test ./RomanNumberTest/bin/Release/RomanNumberTest.dll
